### PR TITLE
Fix incremental build with post-compile-weaving plugin

### PR DESCRIPTION
**Pull request by bigdaz**
The post-compile-weaving plugin was incorrectly adding the compiler output directory to the _task inputs_ for modified compile tasks. This prevents the task from being
marked as UP-TO-DATE after an initial `clean compile`.

 
This fix removes the compiler output directory from the inputs of the modified
compile tasks. Instead, only files added to the `inpath` parameter are considered
to be task inputs. Both the compiler output and the configured `inpath` are still
passed to AJC via the `—inpath` property.

This PR fixes freefair/gradle-plugins#212.

### CODE REVIEW

**Comment by paplorinc** [comment]
Hey @larsgrefer, is there anything else needed to be able to merge this in?

**Comment by larsgrefer** [comment]
Thanks for reporting and fixing this 👍

**Comment by bigdaz** [comment]
@larsgrefer my pleasure. Any idea on when this might be included in a release? (I'm a bit sad that I just missed 5.0.0!)

**Comment by larsgrefer** [comment]
@bigdaz I've just released 5.0.1

**Pull request merged**
